name: campo
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - numpy
  - lue
  - pcraster
  - matplotlib
  - xarray
  - pandas
  - gdal
  - networkx
  - pip
  - pip:
    - https://campo.computationalgeography.org/download/campo-0.0.21-py3-none-any.whl
